### ISSUE TITLE
Bad code generation

### ISSUE THREAD

**Issue by sphilippe-avs** [AVSimulation/SCANeR-Quick-Starts#22]
Hello Guillaume (Adam),
On the page "HT_Download_Trial_SCANeR.md" I found a "bad code generation".
I think it might be due to the new system to add links.
Can you please check?
Thanks,
Sylvain

**Comment by AVSGuillaume** [comment]
Bonjour Sylvain,

I made the correction on the website.
Should be fine now.

I think here is the cause:
When merging the "minor grammatical changes", there was a conflict.
- On your side, there are text corrections, including in the first and last text lines
- On the published side, I added the header and removed the "previous" and "next" links
- I made these changes *after* Terry made a copy (fork) of the files
This resulted in this "merge resolution tags":
![image](https://user-images.githubusercontent.com/76465164/144771002-702a7287-4d05-47da-bc83-1a927c89924f.png)

So to fix this
- Removed all the "merge resolution tags"'
- Kept only the "minor grammatical changes"
- Kept (or restore) the header
- Removed the "previous" and "next" links (if they reappear)
![image](https://user-images.githubusercontent.com/76465164/144771193-80975f81-9d1f-495d-abd0-6d5f3a9587e8.png)

To avoid the issue next time
- When Github notifies the merge conflict, decide to keep HEAD or [new commit] changes by editing the merge conflict file (it normally opens automatically)

It should not happen too often though. This is only due to me making changes over all files at once.

**Comment by AVSGuillaume** [comment]
Also to avoid having more merge conflicts for Terry:
- Discard the current copy : delete terry-avs/SCANeR-Quick-Starts
- Make a copy again: fork from AVSimulation/SCANeR-Quick-Starts to terry-avs
Or when Terry gets access to AVSimulation:
- Make the changes directly on AVSimulation/SCANeR-Quick-Starts
- Use the "Published" branch for instant changes, or a new branch if it needs reviewing before publication.
Maybe clear for you but now it's written just in case ^^'

**Comment by AVSGuillaume** [comment]
I let you close the issue if it's good

**Comment by sphilippe-avs** [comment]
Thank you it's clear!
